#
# RULES
# ~/.config/hypr/settings/rules.conf
#

windowrule = float, class:.*zenity.*|.*blueman.*
windowrule = size 50% 50%, class:.*zenity.*|.*blueman.*
windowrule = float, title:Emulator|Calculator
windowrule = size 20% 50%, title:Calculator
# windowrule = opacity 0.0, focus:0 floating:1
#
windowrule = plugin:hyprbars:nobar, title:.*Brave.*|Calculator|.*Emulator.*|.*Beekeeper.*
windowrule = plugin:hyprbars:nobar, class:.*File Manager.*|.*Nautilus.*|.*zenity.*
