#
# HYPRLAND CONFIGURATION FILE
# ~/.config/hypr/hyprland.conf
# See: `man hyprland` | https://wiki.hyprland.org/
#

source=~/.config/hypr/settings/monitors.conf
source=~/.config/hypr/settings/env.conf
source=~/.config/hypr/settings/plugins.conf
source=~/.config/hypr/settings/keybinds.conf
source=~/.config/hypr/settings/autostart.conf
source=~/.config/hypr/settings/general.conf
source=~/.config/hypr/settings/rules.conf
