# vim:set ft=sh:

MODULES=()

BINARIES=()

FILES=()

HOOKS=(base systemd autodetect microcode modconf kms plymouth keyboard keymap sd-vconsole block btrfs filesystems fsck)

COMPRESSION="zstd"

COMPRESSION_OPTIONS=(-v -5 --long -T0)

MODULES_DECOMPRESS="yes"
