TLP_ENABLE=1

TLP_WARN_LEVEL=3

TLP_DEFAULT_MODE=BAT

TLP_PERSISTENT_DEFAULT=0

DISK_IDLE_SECS_ON_AC=10
DISK_IDLE_SECS_ON_BAT=2

MAX_LOST_WORK_SECS_ON_AC=15
MAX_LOST_WORK_SECS_ON_BAT=60

CPU_DRIVER_OPMODE_ON_AC=guided
CPU_DRIVER_OPMODE_ON_BAT=passive

CPU_SCALING_GOVERNOR_ON_AC=ondemand
CPU_SCALING_GOVERNOR_ON_BAT=powersave

# tlp-stat -p
CPU_SCALING_MIN_FREQ_ON_AC=1100947
CPU_SCALING_MAX_FREQ_ON_AC=4001000
CPU_SCALING_MIN_FREQ_ON_BAT=1100947
CPU_SCALING_MAX_FREQ_ON_BAT=4001000

CPU_ENERGY_PERF_POLICY_ON_AC=balance_performance
CPU_ENERGY_PERF_POLICY_ON_BAT=power

CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0

NMI_WATCHDOG=0

PLATFORM_PROFILE_ON_AC=quiet # balanced
PLATFORM_PROFILE_ON_BAT=quiet

# tlp diskid
DISK_DEVICES="nvme0n1"

DISK_APM_LEVEL_ON_AC="keep"
DISK_APM_LEVEL_ON_BAT="keep"

#DISK_IOSCHED="mq-deadline mq-deadline"

RADEON_DPM_PERF_LEVEL_ON_AC=auto
RADEON_DPM_PERF_LEVEL_ON_BAT=auto

RADEON_DPM_STATE_ON_AC=balanced
RADEON_DPM_STATE_ON_BAT=battery

AMDGPU_ABM_LEVEL_ON_AC=0
AMDGPU_ABM_LEVEL_ON_BAT=1

WIFI_PWR_ON_AC=off
WIFI_PWR_ON_BAT=on

WOL_DISABLE=Y

SOUND_POWER_SAVE_CONTROLLER=Y

PCIE_ASPM_ON_AC=default
PCIE_ASPM_ON_BAT=powersave

RUNTIME_PM_ON_AC=on
RUNTIME_PM_ON_BAT=auto

USB_AUTOSUSPEND=1

DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE="bluetooth nfc wwan"

START_CHARGE_THRESH_BAT0=80
STOP_CHARGE_THRESH_BAT0=90
START_CHARGE_THRESH_BAT1=80
STOP_CHARGE_THRESH_BAT1=90
RESTORE_THRESHOLDS_ON_BAT=1

# tlp-rdw - Parameters for the radio device wizard
DEVICES_TO_DISABLE_ON_LAN_CONNECT="wifi wwan"
DEVICES_TO_DISABLE_ON_WIFI_CONNECT="wwan"
DEVICES_TO_DISABLE_ON_WWAN_CONNECT="wifi"

DEVICES_TO_ENABLE_ON_LAN_DISCONNECT="wifi"
DEVICES_TO_ENABLE_ON_WIFI_DISCONNECT=""
DEVICES_TO_ENABLE_ON_WWAN_DISCONNECT=""

DEVICES_TO_ENABLE_ON_DOCK=""
DEVICES_TO_DISABLE_ON_DOCK=""

DEVICES_TO_ENABLE_ON_UNDOCK="wifi"
DEVICES_TO_DISABLE_ON_UNDOCK=""
