[AdwStyleManager]
color-scheme=ADW_COLOR_SCHEME_PREFER_LIGHT

[Settings]
gtk-alternative-button-order=false
gtk-alternative-sort-arrows=false
gtk-cursor-aspect-ratio=0.040000
gtk-cursor-blink=true
gtk-cursor-blink-time=1200
gtk-cursor-blink-timeout=10
gtk-cursor-theme-name=Adwaita
gtk-cursor-theme-size=21
gtk-decoration-layout=menu:minimize,maximize,close
gtk-dialogs-use-header=true
gtk-dnd-drag-threshold=8
gtk-double-click-distance=5
gtk-double-click-time=400
gtk-enable-accels=true
gtk-enable-animations=true
gtk-enable-event-sounds=true
gtk-enable-input-feedback-sounds=true
gtk-enable-primary-paste=true
gtk-entry-password-hint-timeout=0
gtk-entry-select-on-focus=true
gtk-error-bell=true
gtk-font-name=Noto Sans 11
gtk-fontconfig-timestamp=0
gtk-icon-theme-name=Adwaita
# gtk-im-module=NULL
# gtk-key-theme-name=NULL
gtk-keynav-use-caret=false
gtk-label-select-on-focus=true
gtk-long-press-time=500
# gtk-modules=NULL
gtk-primary-button-warps-slider=true
gtk-print-backends=file,lpr,cups
gtk-print-preview-command=evince --unlink-tempfile --preview --print-settings %s %f
gtk-recent-files-enabled=true
gtk-recent-files-max-age=30
gtk-shell-shows-app-menu=false
gtk-shell-shows-desktop=true
gtk-shell-shows-menubar=false
gtk-sound-theme-name=freedesktop
gtk-split-cursor=true
gtk-theme-name=Adwaita
gtk-titlebar-double-click=toggle-maximize
gtk-titlebar-middle-click=none
gtk-titlebar-right-click=menu
gtk-show-unicode-menu=true
gtk-xft-antialias=-1
gtk-xft-dpi=-1
gtk-xft-hinting=-1
# gtk-xft-hintstyle=NULL
# gtk-xft-rgba=NULL
