#
# FUZZEL CONFIGURATION FILE
# ~/.config/fuzzel/fuzzel.ini
# See: `man fuzzel.ini` | https://man.archlinux.org/man/fuzzel.ini.5
#

[main]
# include=
# output=
font=Noto Sans Mono:size=14
# use-bold=no
dpi-aware=no
# placeholder=""
# prompt="> "
icon-theme=Adwaita
icons-enabled=yes
# hide-before-typing=no
# fields=filename,name,generic
# password-character=*
# match-mode=fzf
# sort-result=yes
# match-counter=no
# filter-desktop=Boolean. Based on the value of XDG_CURRENT_DESKTOP.
# show-actions=no
# launch-prefix=
# anchor=center
# x-margin=0
# y-margin=0
lines=10
width=64
tabs=3
horizontal-pad=16
vertical-pad=16
inner-pad=24
# image-size-ratio=0.5
line-height=24
# letter-spacing=0
# layer=overlay
# keyboard-focus=exclusive
# exit-on-keyboard-focus-loss=yes
# render-workers=the number of available logical CPUs (including SMT)
# match-workers=the number of available logical CPUs (including SMT)
# delayed-filter-ms=300
# delayed-filter-limit=20000
# cache=

[colors]
background=24273add
text=cad3f5ff
prompt=b8c0e0ff
placeholder=8087a2ff
input=cad3f5ff
match=8aadf4ff
selection=5b6078ff
selection-text=cad3f5ff
selection-match=8aadf4ff
counter=8087a2ff
border=8aadf4ff

[border]
width=1
radius=16

[dmenu]
# mode=text
# exit-immediately-if-empty=no

[key-bindings]
# cancel=Control+g Control+c Control+bracketleft Escape
# execute=Return KP_Enter Control+y
# execute-or-next=Tab
# execute-input=Shift+Return Shift+KP_Enter
# cursor-left=Left Control+b
# cursor-left-word=Control+Left Mod1+b
# cursor-right=Right Control+f
# cursor-right-word=Control+Right Mod1+f
# cursor-home=Home Control+a
# cursor-end=End Control+e
# delete-input=Control+k
# delete-line-backward=Control+u
# delete-line-forward=Control+k
# delete-prev=BackSpace Control+h
# delete-prev-word=Mod1+BackSpace Control+BackSpace Control+w
# delete-next=Delete
# delete-next-word=Mod1+d Control+Delete
# insert-selected=Control+Tab
# expunge=Shift+Delete
# clipboard-paste=Control+v XF86Paste
# primary-paste=Shift+Insert Shift+KP_Insert
# prev=Up Control+p
# prev-with-wrap=ISO_Left_Tap
# prev-page=PageUp KP_PageUp
# next=Down Control+n
# next-with-wrap=unbound
# next-page=Page_Down KP_Page_Down
# first=Control+Home
# last=Control+End
# # Execute the currently selected entry, then exit with a non-zero exit code.
# # custom-1 exits with exit code 10, custom-2 with 11, custom-3 with 12, and so on.
# custom-1=Mod1+1
# custom-2=Mod1+2
# custom-3=Mod1+3
# custom-4=Mod1+4
# custom-5=Mod1+5
# custom-6=Mod1+6
# custom-7=Mod1+7
# custom-8=Mod1+8
# custom-9=Mod1+9
# custom-10=Mod1+10
# custom-11=Mod1+11
# custom-12=Mod1+12
# custom-13=Mod1+13
# custom-14=Mod1+14
# custom-15=Mod1+15
# custom-16=Mod1+16
# custom-17=Mod1+17
# custom-18=Mod1+18
# custom-19=Mod1+19
