# Disable NVIDIA proprietary driver
# blacklist nvidia
# blacklist nvidia_drm
# blacklist nvidia_modeset
# blacklist nvidia_uvm

# Disable nouveau (open-source NVIDIA driver)
blacklist nouveau
options nouveau modeset=0
