# This file is used to configure power management options for the NVIDIA driver.
# /etc/modprobe.d/nvidia-pm.conf

# Enables the NVIDIA power management method.
options nvidia "NVreg_PmMethod=1"

# Enable or disable the use of native power management.
# This option allows the driver to manage power states more efficiently.
options nvidia "NVreg_PmUseNativePowerManagement=1"

# Enables the PowerMizer feature, which dynamically adjusts
# the GPU's performance and power consumption based on workload.
options nvidia "NVreg_PmUsePowerMizer=1"

# Default PowerMizer level (0:max performance, 1:adaptive, 2:max power saving)
options nvidia "NVreg_RegistryPowerMizerDefault=1"

# Explicitly enables the PowerMizer feature (more granular control)
options nvidia "NVreg_RegistryDwords=PowerMizerEnable=1"

# Default PowerMizer level (0:max performance, 1:adaptive, 2:max power saving)
options nvidia "NVreg_RegistryDwords=PowerMizerDefault=1"

# Enables GPU clock gating, which allows the GPU
# to reduce its clock speed when idle, saving power.
options nvidia "NVreg_RegistryDwords=EnableGpuClockGating=1"

# Enables memory clock gating, allowing the memory
# to reduce its clock speed when not in use, further saving power.
options nvidia "NVreg_RegistryDwords=EnableMemoryClockGating=1"

# Enables thermal management features, allowing the driver
# to manage the GPU's temperature and prevent overheating.
options nvidia "NVreg_RegistryDwords=EnableThermalManagement=1"

# Enables fan control, allowing the driver to manage
# the GPU's cooling fan based on temperature.
options nvidia "NVreg_RegistryDwords=EnableFanControl=1"

# Enables power-saving features,
# allowing the driver to optimize power consumption.
options nvidia "NVreg_RegistryDwords=EnablePowerSaving=1"

# Enable dynamic power management (0x00 disables)
# See: https://us.download.nvidia.com/XFree86/Linux-x86_64/550.54.14/README/dynamicpowermanagement.html
# This setting is called fine-grained power control.
# With this setting, the NVIDIA GPU driver will allow the GPU to go into its lowest power state
# when no applications are running that use the nvidia driver stack.
# Whenever an application requiring NVIDIA GPU access is started, the GPU is put into an active state.
# When the application exits, the GPU is put into a low power state.
# Additionally, the NVIDIA driver will actively monitor GPU usage while applications using the GPU are running.
# When the applications have not used the GPU for a short period, the driver will allow the GPU to be powered down.
# As soon as the application starts using the GPU, the GPU is reactivated.
options nvidia "NVreg_DynamicPowerManagement=0x02"

# Enables error reporting for power management,
# allowing the driver to log power management-related errors.
options nvidia "NVreg_PmErrorReporting=1"
